create table filial (
    id number(19,0) generated by default as identity,
    cidade varchar2(255 char),
    nome varchar2(255 char),
    pais varchar2(255 char),
    primary key (id)
);

create table patio (
    comprimento float(53),
    largura float(53),
    filial_id number(19,0),
    id number(19,0) generated by default as identity,
    nome varchar2(255 char),
    primary key (id),
    constraint fk_patio_filial foreign key (filial_id) references filial(id)
);

create table tag_rfid (
    ativa number(1,0) not null check (ativa in (0,1)),
    id number(19,0) generated by default as identity,
    codigo_identificacao varchar2(255 char),
    primary key (id)
);

create table leitor_rfid (
    id number(19,0) generated by default as identity,
    patio_id number(19,0),
    ip_dispositivo varchar2(255 char),
    localizacao varchar2(255 char),
    primary key (id),
    constraint fk_leitor_patio foreign key (patio_id) references patio(id)
);

create table leitura_rfid (
    data_hora timestamp(6),
    id number(19,0) generated by default as identity,
    leitor_id number(19,0),
    tag_id number(19,0),
    primary key (id),
    constraint fk_leitura_leitor foreign key (leitor_id) references leitor_rfid(id),
    constraint fk_leitura_tag foreign key (tag_id) references tag_rfid(id)
);

create table moto (
    modelo number(3,0) constraint chk_moto_modelo check (modelo between 0 and 2),
    patio_id number(19,0),
    tag_id number(19,0) constraint uk_moto_tag unique,
    marca varchar2(255 char),
    placa varchar2(255 char) not null,
    status varchar2(255 char) constraint chk_moto_status check (status in ('LIGADO','DESLIGADO','MANUTENCAO','DISPONIVEL')),
    primary key (placa),
    constraint fk_moto_patio foreign key (patio_id) references patio(id),
    constraint fk_moto_tag foreign key (tag_id) references tag_rfid(id)
);

/*
create table usuario (
    roles number(3,0) constraint chk_usuario_roles check (roles between 0 and 1),
    id number(19,0) generated by default as identity,
    password varchar2(255 char),
    username varchar2(255 char),
    primary key (id)
);
*/